<?php

namespace Database\Seeders;

use GuzzleHttp\Client;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;

class CountrySeeder extends Seeder
{
    public $countries = array(
        'AF' => array('id' => 1, 'phone_code' => 93, 'country_name' => 'Afghanistan', 'alpha_3' => 'AFG', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'AX' => array('id' => 2, 'phone_code' => 358, 'country_name' => 'Aland Islands', 'alpha_3' => 'ALA', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'AL' => array('id' => 3, 'phone_code' => 355, 'country_name' => 'Albania', 'alpha_3' => 'ALB', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'DZ' => array('id' => 4, 'phone_code' => 213, 'country_name' => 'Algeria', 'alpha_3' => 'DZA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'AS' => array('id' => 5, 'phone_code' => 1684, 'country_name' => 'American Samoa', 'alpha_3' => 'ASM', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'AD' => array('id' => 6, 'phone_code' => 376, 'country_name' => 'Andorra', 'alpha_3' => 'AND', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'AO' => array('id' => 7, 'phone_code' => 244, 'country_name' => 'Angola', 'alpha_3' => 'AGO', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'AI' => array('id' => 8, 'phone_code' => 1264, 'country_name' => 'Anguilla', 'alpha_3' => 'AIA', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'AQ' => array('id' => 9, 'phone_code' => 672, 'country_name' => 'Antarctica', 'alpha_3' => 'ATA', 'continent_code' => 'AN', 'continent_name' => 'Antarctica'),
        'AG' => array('id' => 10, 'phone_code' => 1268, 'country_name' => 'Antigua and Barbuda', 'alpha_3' => 'ATG', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'AR' => array('id' => 11, 'phone_code' => 54, 'country_name' => 'Argentina', 'alpha_3' => 'ARG', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'AM' => array('id' => 12, 'phone_code' => 374, 'country_name' => 'Armenia', 'alpha_3' => 'ARM', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'AW' => array('id' => 13, 'phone_code' => 297, 'country_name' => 'Aruba', 'alpha_3' => 'ABW', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'AU' => array('id' => 14, 'phone_code' => 61, 'country_name' => 'Australia', 'alpha_3' => 'AUS', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'AT' => array('id' => 15, 'phone_code' => 43, 'country_name' => 'Austria', 'alpha_3' => 'AUT', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'AZ' => array('id' => 16, 'phone_code' => 994, 'country_name' => 'Azerbaijan', 'alpha_3' => 'AZE', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'BS' => array('id' => 17, 'phone_code' => 1242, 'country_name' => 'Bahamas', 'alpha_3' => 'BHS', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'BH' => array('id' => 18, 'phone_code' => 973, 'country_name' => 'Bahrain', 'alpha_3' => 'BHR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'BD' => array('id' => 19, 'phone_code' => 880, 'country_name' => 'Bangladesh', 'alpha_3' => 'BGD', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'BB' => array('id' => 20, 'phone_code' => 1246, 'country_name' => 'Barbados', 'alpha_3' => 'BRB', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'BY' => array('id' => 21, 'phone_code' => 375, 'country_name' => 'Belarus', 'alpha_3' => 'BLR', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'BE' => array('id' => 22, 'phone_code' => 32, 'country_name' => 'Belgium', 'alpha_3' => 'BEL', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'BZ' => array('id' => 23, 'phone_code' => 501, 'country_name' => 'Belize', 'alpha_3' => 'BLZ', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'BJ' => array('id' => 24, 'phone_code' => 229, 'country_name' => 'Benin', 'alpha_3' => 'BEN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'BM' => array('id' => 25, 'phone_code' => 1441, 'country_name' => 'Bermuda', 'alpha_3' => 'BMU', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'BT' => array('id' => 26, 'phone_code' => 975, 'country_name' => 'Bhutan', 'alpha_3' => 'BTN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'BO' => array('id' => 27, 'phone_code' => 591, 'country_name' => 'Bolivia', 'alpha_3' => 'BOL', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'BQ' => array('id' => 28, 'phone_code' => 599, 'country_name' => 'Bonaire, Sint Eustatius and Saba', 'alpha_3' => 'BES', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'BA' => array('id' => 29, 'phone_code' => 387, 'country_name' => 'Bosnia and Herzegovina', 'alpha_3' => 'BIH', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'BW' => array('id' => 30, 'phone_code' => 267, 'country_name' => 'Botswana', 'alpha_3' => 'BWA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'BV' => array('id' => 31, 'phone_code' => 55, 'country_name' => 'Bouvet Island', 'alpha_3' => 'BVT', 'continent_code' => 'AN', 'continent_name' => 'Antarctica'),
        'BR' => array('id' => 32, 'phone_code' => 55, 'country_name' => 'Brazil', 'alpha_3' => 'BRA', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'IO' => array('id' => 33, 'phone_code' => 246, 'country_name' => 'British Indian Ocean Territory', 'alpha_3' => 'IOT', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'BN' => array('id' => 34, 'phone_code' => 673, 'country_name' => 'Brunei Darussalam', 'alpha_3' => 'BRN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'BG' => array('id' => 35, 'phone_code' => 359, 'country_name' => 'Bulgaria', 'alpha_3' => 'BGR', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'BF' => array('id' => 36, 'phone_code' => 226, 'country_name' => 'Burkina Faso', 'alpha_3' => 'BFA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'BI' => array('id' => 37, 'phone_code' => 257, 'country_name' => 'Burundi', 'alpha_3' => 'BDI', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'KH' => array('id' => 38, 'phone_code' => 855, 'country_name' => 'Cambodia', 'alpha_3' => 'KHM', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'CM' => array('id' => 39, 'phone_code' => 237, 'country_name' => 'Cameroon', 'alpha_3' => 'CMR', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'CA' => array('id' => 40, 'phone_code' => 1, 'country_name' => 'Canada', 'alpha_3' => 'CAN', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'CV' => array('id' => 41, 'phone_code' => 238, 'country_name' => 'Cape Verde', 'alpha_3' => 'CPV', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'KY' => array('id' => 42, 'phone_code' => 1345, 'country_name' => 'Cayman Islands', 'alpha_3' => 'CYM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'CF' => array('id' => 43, 'phone_code' => 236, 'country_name' => 'Central African Republic', 'alpha_3' => 'CAF', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'TD' => array('id' => 44, 'phone_code' => 235, 'country_name' => 'Chad', 'alpha_3' => 'TCD', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'CL' => array('id' => 45, 'phone_code' => 56, 'country_name' => 'Chile', 'alpha_3' => 'CHL', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'CN' => array('id' => 46, 'phone_code' => 86, 'country_name' => 'China', 'alpha_3' => 'CHN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'CX' => array('id' => 47, 'phone_code' => 61, 'country_name' => 'Christmas Island', 'alpha_3' => 'CXR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'CC' => array('id' => 48, 'phone_code' => 672, 'country_name' => 'Cocos (Keeling) Islands', 'alpha_3' => 'CCK', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'CO' => array('id' => 49, 'phone_code' => 57, 'country_name' => 'Colombia', 'alpha_3' => 'COL', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'KM' => array('id' => 50, 'phone_code' => 269, 'country_name' => 'Comoros', 'alpha_3' => 'COM', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'CG' => array('id' => 51, 'phone_code' => 242, 'country_name' => 'Congo', 'alpha_3' => 'COG', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'CD' => array('id' => 52, 'phone_code' => 242, 'country_name' => 'Congo, Democratic Republic of the Congo', 'alpha_3' => 'COD', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'CK' => array('id' => 53, 'phone_code' => 682, 'country_name' => 'Cook Islands', 'alpha_3' => 'COK', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'CR' => array('id' => 54, 'phone_code' => 506, 'country_name' => 'Costa Rica', 'alpha_3' => 'CRI', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'CI' => array('id' => 55, 'phone_code' => 225, 'country_name' => 'Cote D\'Ivoire', 'alpha_3' => 'CIV', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'HR' => array('id' => 56, 'phone_code' => 385, 'country_name' => 'Croatia', 'alpha_3' => 'HRV', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'CU' => array('id' => 57, 'phone_code' => 53, 'country_name' => 'Cuba', 'alpha_3' => 'CUB', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'CW' => array('id' => 58, 'phone_code' => 599, 'country_name' => 'Curacao', 'alpha_3' => 'CUW', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'CY' => array('id' => 59, 'phone_code' => 357, 'country_name' => 'Cyprus', 'alpha_3' => 'CYP', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'CZ' => array('id' => 60, 'phone_code' => 420, 'country_name' => 'Czech Republic', 'alpha_3' => 'CZE', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'DK' => array('id' => 61, 'phone_code' => 45, 'country_name' => 'Denmark', 'alpha_3' => 'DNK', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'DJ' => array('id' => 62, 'phone_code' => 253, 'country_name' => 'Djibouti', 'alpha_3' => 'DJI', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'DM' => array('id' => 63, 'phone_code' => 1767, 'country_name' => 'Dominica', 'alpha_3' => 'DMA', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'DO' => array('id' => 64, 'phone_code' => 1809, 'country_name' => 'Dominican Republic', 'alpha_3' => 'DOM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'EC' => array('id' => 65, 'phone_code' => 593, 'country_name' => 'Ecuador', 'alpha_3' => 'ECU', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'EG' => array('id' => 66, 'phone_code' => 20, 'country_name' => 'Egypt', 'alpha_3' => 'EGY', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'SV' => array('id' => 67, 'phone_code' => 503, 'country_name' => 'El Salvador', 'alpha_3' => 'SLV', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'GQ' => array('id' => 68, 'phone_code' => 240, 'country_name' => 'Equatorial Guinea', 'alpha_3' => 'GNQ', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'ER' => array('id' => 69, 'phone_code' => 291, 'country_name' => 'Eritrea', 'alpha_3' => 'ERI', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'EE' => array('id' => 70, 'phone_code' => 372, 'country_name' => 'Estonia', 'alpha_3' => 'EST', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'ET' => array('id' => 71, 'phone_code' => 251, 'country_name' => 'Ethiopia', 'alpha_3' => 'ETH', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'FK' => array('id' => 72, 'phone_code' => 500, 'country_name' => 'Falkland Islands (Malvinas)', 'alpha_3' => 'FLK', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'FO' => array('id' => 73, 'phone_code' => 298, 'country_name' => 'Faroe Islands', 'alpha_3' => 'FRO', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'FJ' => array('id' => 74, 'phone_code' => 679, 'country_name' => 'Fiji', 'alpha_3' => 'FJI', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'FI' => array('id' => 75, 'phone_code' => 358, 'country_name' => 'Finland', 'alpha_3' => 'FIN', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'FR' => array('id' => 76, 'phone_code' => 33, 'country_name' => 'France', 'alpha_3' => 'FRA', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'GF' => array('id' => 77, 'phone_code' => 594, 'country_name' => 'French Guiana', 'alpha_3' => 'GUF', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'PF' => array('id' => 78, 'phone_code' => 689, 'country_name' => 'French Polynesia', 'alpha_3' => 'PYF', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'TF' => array('id' => 79, 'phone_code' => 262, 'country_name' => 'French Southern Territories', 'alpha_3' => 'ATF', 'continent_code' => 'AN', 'continent_name' => 'Antarctica'),
        'GA' => array('id' => 80, 'phone_code' => 241, 'country_name' => 'Gabon', 'alpha_3' => 'GAB', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'GM' => array('id' => 81, 'phone_code' => 220, 'country_name' => 'Gambia', 'alpha_3' => 'GMB', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'GE' => array('id' => 82, 'phone_code' => 995, 'country_name' => 'Georgia', 'alpha_3' => 'GEO', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'DE' => array('id' => 83, 'phone_code' => 49, 'country_name' => 'Germany', 'alpha_3' => 'DEU', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'GH' => array('id' => 84, 'phone_code' => 233, 'country_name' => 'Ghana', 'alpha_3' => 'GHA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'GI' => array('id' => 85, 'phone_code' => 350, 'country_name' => 'Gibraltar', 'alpha_3' => 'GIB', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'GR' => array('id' => 86, 'phone_code' => 30, 'country_name' => 'Greece', 'alpha_3' => 'GRC', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'GL' => array('id' => 87, 'phone_code' => 299, 'country_name' => 'Greenland', 'alpha_3' => 'GRL', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'GD' => array('id' => 88, 'phone_code' => 1473, 'country_name' => 'Grenada', 'alpha_3' => 'GRD', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'GP' => array('id' => 89, 'phone_code' => 590, 'country_name' => 'Guadeloupe', 'alpha_3' => 'GLP', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'GU' => array('id' => 90, 'phone_code' => 1671, 'country_name' => 'Guam', 'alpha_3' => 'GUM', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'GT' => array('id' => 91, 'phone_code' => 502, 'country_name' => 'Guatemala', 'alpha_3' => 'GTM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'GG' => array('id' => 92, 'phone_code' => 44, 'country_name' => 'Guernsey', 'alpha_3' => 'GGY', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'GN' => array('id' => 93, 'phone_code' => 224, 'country_name' => 'Guinea', 'alpha_3' => 'GIN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'GW' => array('id' => 94, 'phone_code' => 245, 'country_name' => 'Guinea-Bissau', 'alpha_3' => 'GNB', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'GY' => array('id' => 95, 'phone_code' => 592, 'country_name' => 'Guyana', 'alpha_3' => 'GUY', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'HT' => array('id' => 96, 'phone_code' => 509, 'country_name' => 'Haiti', 'alpha_3' => 'HTI', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'HM' => array('id' => 97, 'phone_code' => 0, 'country_name' => 'Heard Island and Mcdonald Islands', 'alpha_3' => 'HMD', 'continent_code' => 'AN', 'continent_name' => 'Antarctica'),
        'VA' => array('id' => 98, 'phone_code' => 39, 'country_name' => 'Holy See (Vatican City State)', 'alpha_3' => 'VAT', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'HN' => array('id' => 99, 'phone_code' => 504, 'country_name' => 'Honduras', 'alpha_3' => 'HND', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'HK' => array('id' => 100, 'phone_code' => 852, 'country_name' => 'Hong Kong', 'alpha_3' => 'HKG', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'HU' => array('id' => 101, 'phone_code' => 36, 'country_name' => 'Hungary', 'alpha_3' => 'HUN', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'IS' => array('id' => 102, 'phone_code' => 354, 'country_name' => 'Iceland', 'alpha_3' => 'ISL', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'IN' => array('id' => 103, 'phone_code' => 91, 'country_name' => 'India', 'alpha_3' => 'IND', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'ID' => array('id' => 104, 'phone_code' => 62, 'country_name' => 'Indonesia', 'alpha_3' => 'IDN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'IR' => array('id' => 105, 'phone_code' => 98, 'country_name' => 'Iran, Islamic Republic of', 'alpha_3' => 'IRN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'IQ' => array('id' => 106, 'phone_code' => 964, 'country_name' => 'Iraq', 'alpha_3' => 'IRQ', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'IE' => array('id' => 107, 'phone_code' => 353, 'country_name' => 'Ireland', 'alpha_3' => 'IRL', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'IM' => array('id' => 108, 'phone_code' => 44, 'country_name' => 'Isle of Man', 'alpha_3' => 'IMN', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'IL' => array('id' => 109, 'phone_code' => 972, 'country_name' => 'Israel', 'alpha_3' => 'ISR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'IT' => array('id' => 110, 'phone_code' => 39, 'country_name' => 'Italy', 'alpha_3' => 'ITA', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'JM' => array('id' => 111, 'phone_code' => 1876, 'country_name' => 'Jamaica', 'alpha_3' => 'JAM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'JP' => array('id' => 112, 'phone_code' => 81, 'country_name' => 'Japan', 'alpha_3' => 'JPN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'JE' => array('id' => 113, 'phone_code' => 44, 'country_name' => 'Jersey', 'alpha_3' => 'JEY', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'JO' => array('id' => 114, 'phone_code' => 962, 'country_name' => 'Jordan', 'alpha_3' => 'JOR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'KZ' => array('id' => 115, 'phone_code' => 7, 'country_name' => 'Kazakhstan', 'alpha_3' => 'KAZ', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'KE' => array('id' => 116, 'phone_code' => 254, 'country_name' => 'Kenya', 'alpha_3' => 'KEN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'KI' => array('id' => 117, 'phone_code' => 686, 'country_name' => 'Kiribati', 'alpha_3' => 'KIR', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'KP' => array('id' => 118, 'phone_code' => 850, 'country_name' => 'Korea, Democratic People\'s Republic of', 'alpha_3' => 'PRK', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'KR' => array('id' => 119, 'phone_code' => 82, 'country_name' => 'Korea, Republic of', 'alpha_3' => 'KOR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'XK' => array('id' => 120, 'phone_code' => 381, 'country_name' => 'Kosovo', 'alpha_3' => 'XKX', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'KW' => array('id' => 121, 'phone_code' => 965, 'country_name' => 'Kuwait', 'alpha_3' => 'KWT', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'KG' => array('id' => 122, 'phone_code' => 996, 'country_name' => 'Kyrgyzstan', 'alpha_3' => 'KGZ', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'LA' => array('id' => 123, 'phone_code' => 856, 'country_name' => 'Lao People\'s Democratic Republic', 'alpha_3' => 'LAO', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'LV' => array('id' => 124, 'phone_code' => 371, 'country_name' => 'Latvia', 'alpha_3' => 'LVA', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'LB' => array('id' => 125, 'phone_code' => 961, 'country_name' => 'Lebanon', 'alpha_3' => 'LBN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'LS' => array('id' => 126, 'phone_code' => 266, 'country_name' => 'Lesotho', 'alpha_3' => 'LSO', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'LR' => array('id' => 127, 'phone_code' => 231, 'country_name' => 'Liberia', 'alpha_3' => 'LBR', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'LY' => array('id' => 128, 'phone_code' => 218, 'country_name' => 'Libyan Arab Jamahiriya', 'alpha_3' => 'LBY', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'LI' => array('id' => 129, 'phone_code' => 423, 'country_name' => 'Liechtenstein', 'alpha_3' => 'LIE', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'LT' => array('id' => 130, 'phone_code' => 370, 'country_name' => 'Lithuania', 'alpha_3' => 'LTU', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'LU' => array('id' => 131, 'phone_code' => 352, 'country_name' => 'Luxembourg', 'alpha_3' => 'LUX', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'MO' => array('id' => 132, 'phone_code' => 853, 'country_name' => 'Macao', 'alpha_3' => 'MAC', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'MK' => array('id' => 133, 'phone_code' => 389, 'country_name' => 'Macedonia, the Former Yugoslav Republic of', 'alpha_3' => 'MKD', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'MG' => array('id' => 134, 'phone_code' => 261, 'country_name' => 'Madagascar', 'alpha_3' => 'MDG', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MW' => array('id' => 135, 'phone_code' => 265, 'country_name' => 'Malawi', 'alpha_3' => 'MWI', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MY' => array('id' => 136, 'phone_code' => 60, 'country_name' => 'Malaysia', 'alpha_3' => 'MYS', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'MV' => array('id' => 137, 'phone_code' => 960, 'country_name' => 'Maldives', 'alpha_3' => 'MDV', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'ML' => array('id' => 138, 'phone_code' => 223, 'country_name' => 'Mali', 'alpha_3' => 'MLI', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MT' => array('id' => 139, 'phone_code' => 356, 'country_name' => 'Malta', 'alpha_3' => 'MLT', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'MH' => array('id' => 140, 'phone_code' => 692, 'country_name' => 'Marshall Islands', 'alpha_3' => 'MHL', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'MQ' => array('id' => 141, 'phone_code' => 596, 'country_name' => 'Martinique', 'alpha_3' => 'MTQ', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'MR' => array('id' => 142, 'phone_code' => 222, 'country_name' => 'Mauritania', 'alpha_3' => 'MRT', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MU' => array('id' => 143, 'phone_code' => 230, 'country_name' => 'Mauritius', 'alpha_3' => 'MUS', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'YT' => array('id' => 144, 'phone_code' => 269, 'country_name' => 'Mayotte', 'alpha_3' => 'MYT', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MX' => array('id' => 145, 'phone_code' => 52, 'country_name' => 'Mexico', 'alpha_3' => 'MEX', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'FM' => array('id' => 146, 'phone_code' => 691, 'country_name' => 'Micronesia, Federated States of', 'alpha_3' => 'FSM', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'MD' => array('id' => 147, 'phone_code' => 373, 'country_name' => 'Moldova, Republic of', 'alpha_3' => 'MDA', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'MC' => array('id' => 148, 'phone_code' => 377, 'country_name' => 'Monaco', 'alpha_3' => 'MCO', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'MN' => array('id' => 149, 'phone_code' => 976, 'country_name' => 'Mongolia', 'alpha_3' => 'MNG', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'ME' => array('id' => 150, 'phone_code' => 382, 'country_name' => 'Montenegro', 'alpha_3' => 'MNE', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'MS' => array('id' => 151, 'phone_code' => 1664, 'country_name' => 'Montserrat', 'alpha_3' => 'MSR', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'MA' => array('id' => 152, 'phone_code' => 212, 'country_name' => 'Morocco', 'alpha_3' => 'MAR', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MZ' => array('id' => 153, 'phone_code' => 258, 'country_name' => 'Mozambique', 'alpha_3' => 'MOZ', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'MM' => array('id' => 154, 'phone_code' => 95, 'country_name' => 'Myanmar', 'alpha_3' => 'MMR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'NA' => array('id' => 155, 'phone_code' => 264, 'country_name' => 'Namibia', 'alpha_3' => 'NAM', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'NR' => array('id' => 156, 'phone_code' => 674, 'country_name' => 'Nauru', 'alpha_3' => 'NRU', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'NP' => array('id' => 157, 'phone_code' => 977, 'country_name' => 'Nepal', 'alpha_3' => 'NPL', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'NL' => array('id' => 158, 'phone_code' => 31, 'country_name' => 'Netherlands', 'alpha_3' => 'NLD', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'AN' => array('id' => 159, 'phone_code' => 599, 'country_name' => 'Netherlands Antilles', 'alpha_3' => 'ANT', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'NC' => array('id' => 160, 'phone_code' => 687, 'country_name' => 'New Caledonia', 'alpha_3' => 'NCL', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'NZ' => array('id' => 161, 'phone_code' => 64, 'country_name' => 'New Zealand', 'alpha_3' => 'NZL', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'NI' => array('id' => 162, 'phone_code' => 505, 'country_name' => 'Nicaragua', 'alpha_3' => 'NIC', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'NE' => array('id' => 163, 'phone_code' => 227, 'country_name' => 'Niger', 'alpha_3' => 'NER', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'NG' => array('id' => 164, 'phone_code' => 234, 'country_name' => 'Nigeria', 'alpha_3' => 'NGA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'NU' => array('id' => 165, 'phone_code' => 683, 'country_name' => 'Niue', 'alpha_3' => 'NIU', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'NF' => array('id' => 166, 'phone_code' => 672, 'country_name' => 'Norfolk Island', 'alpha_3' => 'NFK', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'MP' => array('id' => 167, 'phone_code' => 1670, 'country_name' => 'Northern Mariana Islands', 'alpha_3' => 'MNP', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'NO' => array('id' => 168, 'phone_code' => 47, 'country_name' => 'Norway', 'alpha_3' => 'NOR', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'OM' => array('id' => 169, 'phone_code' => 968, 'country_name' => 'Oman', 'alpha_3' => 'OMN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'PK' => array('id' => 170, 'phone_code' => 92, 'country_name' => 'Pakistan', 'alpha_3' => 'PAK', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'PW' => array('id' => 171, 'phone_code' => 680, 'country_name' => 'Palau', 'alpha_3' => 'PLW', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'PS' => array('id' => 172, 'phone_code' => 970, 'country_name' => 'Palestinian Territory, Occupied', 'alpha_3' => 'PSE', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'PA' => array('id' => 173, 'phone_code' => 507, 'country_name' => 'Panama', 'alpha_3' => 'PAN', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'PG' => array('id' => 174, 'phone_code' => 675, 'country_name' => 'Papua New Guinea', 'alpha_3' => 'PNG', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'PY' => array('id' => 175, 'phone_code' => 595, 'country_name' => 'Paraguay', 'alpha_3' => 'PRY', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'PE' => array('id' => 176, 'phone_code' => 51, 'country_name' => 'Peru', 'alpha_3' => 'PER', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'PH' => array('id' => 177, 'phone_code' => 63, 'country_name' => 'Philippines', 'alpha_3' => 'PHL', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'PN' => array('id' => 178, 'phone_code' => 64, 'country_name' => 'Pitcairn', 'alpha_3' => 'PCN', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'PL' => array('id' => 179, 'phone_code' => 48, 'country_name' => 'Poland', 'alpha_3' => 'POL', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'PT' => array('id' => 180, 'phone_code' => 351, 'country_name' => 'Portugal', 'alpha_3' => 'PRT', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'PR' => array('id' => 181, 'phone_code' => 1787, 'country_name' => 'Puerto Rico', 'alpha_3' => 'PRI', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'QA' => array('id' => 182, 'phone_code' => 974, 'country_name' => 'Qatar', 'alpha_3' => 'QAT', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'RE' => array('id' => 183, 'phone_code' => 262, 'country_name' => 'Reunion', 'alpha_3' => 'REU', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'RO' => array('id' => 184, 'phone_code' => 40, 'country_name' => 'Romania', 'alpha_3' => 'ROM', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'RU' => array('id' => 185, 'phone_code' => 70, 'country_name' => 'Russian Federation', 'alpha_3' => 'RUS', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'RW' => array('id' => 186, 'phone_code' => 250, 'country_name' => 'Rwanda', 'alpha_3' => 'RWA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'BL' => array('id' => 187, 'phone_code' => 590, 'country_name' => 'Saint Barthelemy', 'alpha_3' => 'BLM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'SH' => array('id' => 188, 'phone_code' => 290, 'country_name' => 'Saint Helena', 'alpha_3' => 'SHN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'KN' => array('id' => 189, 'phone_code' => 1869, 'country_name' => 'Saint Kitts and Nevis', 'alpha_3' => 'KNA', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'LC' => array('id' => 190, 'phone_code' => 1758, 'country_name' => 'Saint Lucia', 'alpha_3' => 'LCA', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'MF' => array('id' => 191, 'phone_code' => 590, 'country_name' => 'Saint Martin', 'alpha_3' => 'MAF', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'PM' => array('id' => 192, 'phone_code' => 508, 'country_name' => 'Saint Pierre and Miquelon', 'alpha_3' => 'SPM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'VC' => array('id' => 193, 'phone_code' => 1784, 'country_name' => 'Saint Vincent and the Grenadines', 'alpha_3' => 'VCT', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'WS' => array('id' => 194, 'phone_code' => 684, 'country_name' => 'Samoa', 'alpha_3' => 'WSM', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'SM' => array('id' => 195, 'phone_code' => 378, 'country_name' => 'San Marino', 'alpha_3' => 'SMR', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'ST' => array('id' => 196, 'phone_code' => 239, 'country_name' => 'Sao Tome and Principe', 'alpha_3' => 'STP', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'SA' => array('id' => 197, 'phone_code' => 966, 'country_name' => 'Saudi Arabia', 'alpha_3' => 'SAU', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'SN' => array('id' => 198, 'phone_code' => 221, 'country_name' => 'Senegal', 'alpha_3' => 'SEN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'RS' => array('id' => 199, 'phone_code' => 381, 'country_name' => 'Serbia', 'alpha_3' => 'SRB', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'CS' => array('id' => 200, 'phone_code' => 381, 'country_name' => 'Serbia and Montenegro', 'alpha_3' => 'SCG', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'SC' => array('id' => 201, 'phone_code' => 248, 'country_name' => 'Seychelles', 'alpha_3' => 'SYC', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'SL' => array('id' => 202, 'phone_code' => 232, 'country_name' => 'Sierra Leone', 'alpha_3' => 'SLE', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'SG' => array('id' => 203, 'phone_code' => 65, 'country_name' => 'Singapore', 'alpha_3' => 'SGP', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'SX' => array('id' => 204, 'phone_code' => 1, 'country_name' => 'Sint Maarten', 'alpha_3' => 'SXM', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'SK' => array('id' => 205, 'phone_code' => 421, 'country_name' => 'Slovakia', 'alpha_3' => 'SVK', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'SI' => array('id' => 206, 'phone_code' => 386, 'country_name' => 'Slovenia', 'alpha_3' => 'SVN', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'SB' => array('id' => 207, 'phone_code' => 677, 'country_name' => 'Solomon Islands', 'alpha_3' => 'SLB', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'SO' => array('id' => 208, 'phone_code' => 252, 'country_name' => 'Somalia', 'alpha_3' => 'SOM', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'ZA' => array('id' => 209, 'phone_code' => 27, 'country_name' => 'South Africa', 'alpha_3' => 'ZAF', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'GS' => array('id' => 210, 'phone_code' => 500, 'country_name' => 'South Georgia and the South Sandwich Islands', 'alpha_3' => 'SGS', 'continent_code' => 'AN', 'continent_name' => 'Antarctica'),
        'SS' => array('id' => 211, 'phone_code' => 211, 'country_name' => 'South Sudan', 'alpha_3' => 'SSD', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'ES' => array('id' => 212, 'phone_code' => 34, 'country_name' => 'Spain', 'alpha_3' => 'ESP', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'LK' => array('id' => 213, 'phone_code' => 94, 'country_name' => 'Sri Lanka', 'alpha_3' => 'LKA', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'SD' => array('id' => 214, 'phone_code' => 249, 'country_name' => 'Sudan', 'alpha_3' => 'SDN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'SR' => array('id' => 215, 'phone_code' => 597, 'country_name' => 'Suriname', 'alpha_3' => 'SUR', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'SJ' => array('id' => 216, 'phone_code' => 47, 'country_name' => 'Svalbard and Jan Mayen', 'alpha_3' => 'SJM', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'SZ' => array('id' => 217, 'phone_code' => 268, 'country_name' => 'Swaziland', 'alpha_3' => 'SWZ', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'SE' => array('id' => 218, 'phone_code' => 46, 'country_name' => 'Sweden', 'alpha_3' => 'SWE', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'CH' => array('id' => 219, 'phone_code' => 41, 'country_name' => 'Switzerland', 'alpha_3' => 'CHE', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'SY' => array('id' => 220, 'phone_code' => 963, 'country_name' => 'Syrian Arab Republic', 'alpha_3' => 'SYR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TW' => array('id' => 221, 'phone_code' => 886, 'country_name' => 'Taiwan, Province of China', 'alpha_3' => 'TWN', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TJ' => array('id' => 222, 'phone_code' => 992, 'country_name' => 'Tajikistan', 'alpha_3' => 'TJK', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TZ' => array('id' => 223, 'phone_code' => 255, 'country_name' => 'Tanzania, United Republic of', 'alpha_3' => 'TZA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'TH' => array('id' => 224, 'phone_code' => 66, 'country_name' => 'Thailand', 'alpha_3' => 'THA', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TL' => array('id' => 225, 'phone_code' => 670, 'country_name' => 'Timor-Leste', 'alpha_3' => 'TLS', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TG' => array('id' => 226, 'phone_code' => 228, 'country_name' => 'Togo', 'alpha_3' => 'TGO', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'TK' => array('id' => 227, 'phone_code' => 690, 'country_name' => 'Tokelau', 'alpha_3' => 'TKL', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'TO' => array('id' => 228, 'phone_code' => 676, 'country_name' => 'Tonga', 'alpha_3' => 'TON', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'TT' => array('id' => 229, 'phone_code' => 1868, 'country_name' => 'Trinidad and Tobago', 'alpha_3' => 'TTO', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'TN' => array('id' => 230, 'phone_code' => 216, 'country_name' => 'Tunisia', 'alpha_3' => 'TUN', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'TR' => array('id' => 231, 'phone_code' => 90, 'country_name' => 'Turkey', 'alpha_3' => 'TUR', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TM' => array('id' => 232, 'phone_code' => 7370, 'country_name' => 'Turkmenistan', 'alpha_3' => 'TKM', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'TC' => array('id' => 233, 'phone_code' => 1649, 'country_name' => 'Turks and Caicos Islands', 'alpha_3' => 'TCA', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'TV' => array('id' => 234, 'phone_code' => 688, 'country_name' => 'Tuvalu', 'alpha_3' => 'TUV', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'UG' => array('id' => 235, 'phone_code' => 256, 'country_name' => 'Uganda', 'alpha_3' => 'UGA', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'UA' => array('id' => 236, 'phone_code' => 380, 'country_name' => 'Ukraine', 'alpha_3' => 'UKR', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'AE' => array('id' => 237, 'phone_code' => 971, 'country_name' => 'United Arab Emirates', 'alpha_3' => 'ARE', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'GB' => array('id' => 238, 'phone_code' => 44, 'country_name' => 'United Kingdom', 'alpha_3' => 'GBR', 'continent_code' => 'EU', 'continent_name' => 'Europe'),
        'US' => array('id' => 239, 'phone_code' => 1, 'country_name' => 'United States', 'alpha_3' => 'USA', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'UM' => array('id' => 240, 'phone_code' => 1, 'country_name' => 'United States Minor Outlying Islands', 'alpha_3' => 'UMI', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'UY' => array('id' => 241, 'phone_code' => 598, 'country_name' => 'Uruguay', 'alpha_3' => 'URY', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'UZ' => array('id' => 242, 'phone_code' => 998, 'country_name' => 'Uzbekistan', 'alpha_3' => 'UZB', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'VU' => array('id' => 243, 'phone_code' => 678, 'country_name' => 'Vanuatu', 'alpha_3' => 'VUT', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'VE' => array('id' => 244, 'phone_code' => 58, 'country_name' => 'Venezuela', 'alpha_3' => 'VEN', 'continent_code' => 'SA', 'continent_name' => 'South America'),
        'VN' => array('id' => 245, 'phone_code' => 84, 'country_name' => 'Viet Nam', 'alpha_3' => 'VNM', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'VG' => array('id' => 246, 'phone_code' => 1284, 'country_name' => 'Virgin Islands, British', 'alpha_3' => 'VGB', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'VI' => array('id' => 247, 'phone_code' => 1340, 'country_name' => 'Virgin Islands, U.s.', 'alpha_3' => 'VIR', 'continent_code' => 'NA', 'continent_name' => 'North America'),
        'WF' => array('id' => 248, 'phone_code' => 681, 'country_name' => 'Wallis and Futuna', 'alpha_3' => 'WLF', 'continent_code' => 'OC', 'continent_name' => 'Oceania'),
        'EH' => array('id' => 249, 'phone_code' => 212, 'country_name' => 'Western Sahara', 'alpha_3' => 'ESH', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'YE' => array('id' => 250, 'phone_code' => 967, 'country_name' => 'Yemen', 'alpha_3' => 'YEM', 'continent_code' => 'AS', 'continent_name' => 'Asia'),
        'ZM' => array('id' => 251, 'phone_code' => 260, 'country_name' => 'Zambia', 'alpha_3' => 'ZMB', 'continent_code' => 'AF', 'continent_name' => 'Africa'),
        'ZW' => array('id' => 252, 'phone_code' => 263, 'country_name' => 'Zimbabwe', 'alpha_3' => 'ZWE', 'continent_code' => 'AF', 'continent_name' => 'Africa')
    );

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect($this->countries)->map(function ($country, $country_code) {
            DB::table('countries')->insert([
                'phone_code' => $country['phone_code'],
                'code' => $country_code,
                'name' => $country['country_name'],
                'alpha_3' => $country['alpha_3'],
                'continent_code' => $country['continent_code'],
                'continent_name' => $country['continent_name'],
            ]);
        });
    }
}
